# This is a generated file, all modifications will be overwritten!

# Describes the default environment variables, secrets the deployment template and the service for the custom jore4 map-matching database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jore4-mapmatchingdb
  namespace: hsl-jore4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "jore4-mapmatchingdb"
  template:
    metadata:
      labels:
        app: "jore4-mapmatchingdb"
    spec:
      restartPolicy: Always
      containers:
        - name: "jore4-mapmatchingdb-image"
          image: "pgrouting/pgrouting:13-3.1-3.2.0"
          imagePullPolicy: Always
          ports:
          - containerPort: 5432
          envFrom:
            - configMapRef:
                name: "jore4-mapmatchingdb-env"

---
apiVersion: v1
kind: Service
metadata:
  name: jore4-mapmatchingdb
  namespace: hsl-jore4
spec:
  type: ClusterIP
  selector:
    app: jore4-mapmatchingdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "jore4-mapmatchingdb-env"
  namespace: hsl-jore4
data:
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_DB: "jore4mapmatching"
  POSTGRES_PASSWORD: "changethis"
  POSTGRES_USER: "changethis"



---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: hsl-jore4
  name: "jore4-foo-storage"
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: hsl-jore4
  name: azure-managed-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi


