# This is a generated file, all modifications will be overwritten!

---
version: "3.8"
services:
  jore4-auth:
    container_name: "auth"
    # you may replace the bundled docker image by setting $AUTH_DOCKER_IMAGE
    image: "${AUTH_DOCKER_IMAGE:-hsldevcom/jore4-auth:main--7655eaf0456a0fcacfa2fd542e68c2e66385e5db}"
    restart: "unless-stopped"
    networks:
      - jore4
    environment:
      API_PATH_PREFIX: ""
      API_PATH_PREFIX_PUBLIC: "/api/auth"
      DB_SESSION_SCHEMA: "public"
      LOGINPAGE_URL: "http://localhost:3300"
      LOGOUTPAGE_URL: "http://localhost:3300"
      OIDC_PROVIDER_BASE_URL: "https://hslid-dev.t5.fi"
      SECRET_STORE_BASE_PATH: "/mnt/secrets-store"
      SELF_PUBLIC_BASE_URL: "http://localhost:3300"
    ports:
      - "127.0.0.1:3200:8080"
    secrets:
      - source: auth-db-hostname
        target: /mnt/secrets-store/db-hostname
      - source: auth-db-name
        target: /mnt/secrets-store/db-name
      - source: auth-db-password
        target: /mnt/secrets-store/db-password
      - source: auth-db-session-schema
        target: /mnt/secrets-store/db-session-schema
      - source: auth-db-username
        target: /mnt/secrets-store/db-username
      - source: auth-oidc-client-id
        target: /mnt/secrets-store/oidc-client-id
      - source: auth-oidc-client-secret
        target: /mnt/secrets-store/oidc-client-secret
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jore4-hasura:
    container_name: "hasura"
    # you may replace the bundled docker image by setting $HASURA_DOCKER_IMAGE
    image: "${HASURA_DOCKER_IMAGE:-hsldevcom/jore4-hasura:hsl-main--20220915-a4b59e4e447c2573025a6f971f114b3ffa6fe0f2}"
    restart: "unless-stopped"
    networks:
      - jore4
    environment:
      HASURA_GRAPHQL_AUTH_HOOK: "http://jore4-auth:8080/public/v1/hasura/webhook"
      HASURA_GRAPHQL_AUTH_HOOK_MODE: "GET"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_METADATA_DIR: "/hasura-metadata"
      HASURA_GRAPHQL_MIGRATIONS_DIR: "/hasura-migrations"
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: "60"
      SECRET_STORE_BASE_PATH: "/mnt/secrets-store"
    ports:
      - "127.0.0.1:3201:8080"
    secrets:
      - source: hasura-db-auth-username
        target: /mnt/secrets-store/db-auth-username
      - source: hasura-db-hostname
        target: /mnt/secrets-store/db-hostname
      - source: hasura-db-jore3importer-username
        target: /mnt/secrets-store/db-jore3importer-username
      - source: hasura-db-name
        target: /mnt/secrets-store/db-name
      - source: hasura-db-password
        target: /mnt/secrets-store/db-password
      - source: hasura-db-timetables-name
        target: /mnt/secrets-store/db-timetables-name
      - source: hasura-db-username
        target: /mnt/secrets-store/db-username
      - source: hasura-hasura-admin-secret
        target: /mnt/secrets-store/hasura-admin-secret
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jore4-jore3importer:
    container_name: "jore3importer"
    # you may replace the bundled docker image by setting $JORE3IMPORTER_DOCKER_IMAGE
    image: "${JORE3IMPORTER_DOCKER_IMAGE:-hsldevcom/jore4-jore3-importer:main--20220912-447a7323444dd3588253e3f53a9ba56d67bdd5c7}"
    restart: "unless-stopped"
    networks:
      - jore4
    environment:
      DIGIROAD_STOPS_CSV_VERSION: "2022-02-03"
      MAP_MATCHING_API_BASEURL: "http://localhost:3005/api/mapmatching"
      SECRET_STORE_BASE_PATH: "/mnt/secrets-store"
    ports:
      - "127.0.0.1:3004:8080"
    secrets:
      - source: jore3importer-importer-db-database
        target: /mnt/secrets-store/importer-db-database
      - source: jore3importer-importer-db-hostname
        target: /mnt/secrets-store/importer-db-hostname
      - source: jore3importer-importer-db-password
        target: /mnt/secrets-store/importer-db-password
      - source: jore3importer-importer-db-username
        target: /mnt/secrets-store/importer-db-username
      - source: jore3importer-jore4-db-database
        target: /mnt/secrets-store/jore4-db-database
      - source: jore3importer-jore4-db-hostname
        target: /mnt/secrets-store/jore4-db-hostname
      - source: jore3importer-jore4-db-password
        target: /mnt/secrets-store/jore4-db-password
      - source: jore3importer-jore4-db-username
        target: /mnt/secrets-store/jore4-db-username
      - source: jore3importer-source-db-database
        target: /mnt/secrets-store/source-db-database
      - source: jore3importer-source-db-hostname
        target: /mnt/secrets-store/source-db-hostname
      - source: jore3importer-source-db-password
        target: /mnt/secrets-store/source-db-password
      - source: jore3importer-source-db-port
        target: /mnt/secrets-store/source-db-port
      - source: jore3importer-source-db-username
        target: /mnt/secrets-store/source-db-username
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jore4-mapmatching:
    container_name: "mapmatching"
    # you may replace the bundled docker image by setting $MAPMATCHING_DOCKER_IMAGE
    image: "${MAPMATCHING_DOCKER_IMAGE:-hsldevcom/jore4-map-matching:main--20220920-e18fc718d801be4540a68228cabb69b226680bbd}"
    restart: "unless-stopped"
    networks:
      - jore4
    environment:
      DB_DATABASE: "jore4mapmatching"
      DB_HOSTNAME: "jore4-mapmatchingdb"
      SECRET_STORE_BASE_PATH: "/mnt/secrets-store"
    ports:
      - "127.0.0.1:3005:8080"
    secrets:
      - source: mapmatching-db-password
        target: /mnt/secrets-store/db-password
      - source: mapmatching-db-username
        target: /mnt/secrets-store/db-username
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jore4-mapmatchingdb:
    container_name: "mapmatchingdb"
    # you may replace the bundled docker image by setting $MAPMATCHINGDB_DOCKER_IMAGE
    image: "${MAPMATCHINGDB_DOCKER_IMAGE:-hsldevcom/jore4-postgres:mapmatching-main--20221013-3b858241030387b2abd68b5def08d9440c3340d3}"
    restart: "unless-stopped"
    networks:
      - jore4
    environment:
      DIGIROAD_ROUTING_DUMP_VERSION: "2022-06-09"
      POSTGRES_DB: "jore4mapmatching"
      SECRET_STORE_BASE_PATH: "/mnt/secrets-store"
    ports:
      - "127.0.0.1:6433:5432"
    secrets:
      - source: mapmatchingdb-postgres-password
        target: /mnt/secrets-store/postgres-password
      - source: mapmatchingdb-postgres-user
        target: /mnt/secrets-store/postgres-user
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jore4-mbtiles:
    container_name: "mbtiles"
    # you may replace the bundled docker image by setting $MBTILES_DOCKER_IMAGE
    image: "${MBTILES_DOCKER_IMAGE:-hsldevcom/jore4-mbtiles-server:main--3cc33ba369a0ad472b88de49baf201895eccc298}"
    restart: "unless-stopped"
    networks:
      - jore4
    environment:
      DR_LINKKI_TILES_URL: "https://jore4storage.blob.core.windows.net/jore4-ui/dr_linkki_2022-06-27.mbtiles"
    ports:
      - "127.0.0.1:3203:8000"

  jore4-mssqltestdb:
    container_name: "mssqltestdb"
    # you may replace the bundled docker image by setting $MSSQLTESTDB_DOCKER_IMAGE
    image: "${MSSQLTESTDB_DOCKER_IMAGE:-hsldevcom/jore4-mssql-testdb:schema-only-main--21ef30b56e38b0cfa118ccf610ba0fa7e9e00ef7}"
    restart: "unless-stopped"
    networks:
      - jore4
    environment:
      SA_PASSWORD: "P@ssw0rd"
    ports:
      - "127.0.0.1:1433:1433"

  jore4-testdb:
    container_name: "testdb"
    # you may replace the bundled docker image by setting $TESTDB_DOCKER_IMAGE
    image: "${TESTDB_DOCKER_IMAGE:-hsldevcom/jore4-postgres:azuredbmock-main--20220927-da89e4bbcaab4433f0a74e669f666e42f037b43c}"
    restart: "unless-stopped"
    networks:
      - jore4
    environment:
      POSTGRES_DB: "jore4e2e"
      POSTGRES_PASSWORD: "adminpassword"
      POSTGRES_USER: "dbadmin"
      SECRET_STORE_BASE_PATH: "/mnt/secrets-store"
    ports:
      - "127.0.0.1:6432:5432"
    secrets:
      - source: testdb-db-auth-name
        target: /mnt/secrets-store/db-auth-name
      - source: testdb-db-auth-password
        target: /mnt/secrets-store/db-auth-password
      - source: testdb-db-auth-username
        target: /mnt/secrets-store/db-auth-username
      - source: testdb-db-hasura-name
        target: /mnt/secrets-store/db-hasura-name
      - source: testdb-db-hasura-password
        target: /mnt/secrets-store/db-hasura-password
      - source: testdb-db-hasura-username
        target: /mnt/secrets-store/db-hasura-username
      - source: testdb-db-jore3importer-name
        target: /mnt/secrets-store/db-jore3importer-name
      - source: testdb-db-jore3importer-password
        target: /mnt/secrets-store/db-jore3importer-password
      - source: testdb-db-jore3importer-username
        target: /mnt/secrets-store/db-jore3importer-username
      - source: testdb-db-timetables-name
        target: /mnt/secrets-store/db-timetables-name
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jore4-ui:
    container_name: "ui"
    # you may replace the bundled docker image by setting $UI_DOCKER_IMAGE
    image: "${UI_DOCKER_IMAGE:-hsldevcom/jore4-ui:main--20221011-06bc484b5366dff627464b0fdc8b736bb58071df}"
    restart: "unless-stopped"
    networks:
      - jore4
    ports:
      - "127.0.0.1:3302:80"

  jore4-proxy:
    container_name: proxy
    image: nginx:alpine
    restart: "unless-stopped"
    networks:
      - jore4
    ports:
      - "127.0.0.1:3300:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  jore4:

secrets:
  auth-db-hostname:
    file: ./secret-auth-db-hostname
  auth-db-name:
    file: ./secret-auth-db-name
  auth-db-password:
    file: ./secret-auth-db-password
  auth-db-session-schema:
    file: ./secret-auth-db-session-schema
  auth-db-username:
    file: ./secret-auth-db-username
  auth-oidc-client-id:
    file: ./secret-auth-oidc-client-id
  auth-oidc-client-secret:
    file: ./secret-auth-oidc-client-secret
  hasura-db-auth-username:
    file: ./secret-hasura-db-auth-username
  hasura-db-hostname:
    file: ./secret-hasura-db-hostname
  hasura-db-jore3importer-username:
    file: ./secret-hasura-db-jore3importer-username
  hasura-db-name:
    file: ./secret-hasura-db-name
  hasura-db-password:
    file: ./secret-hasura-db-password
  hasura-db-timetables-name:
    file: ./secret-hasura-db-timetables-name
  hasura-db-username:
    file: ./secret-hasura-db-username
  hasura-hasura-admin-secret:
    file: ./secret-hasura-hasura-admin-secret
  jore3importer-importer-db-database:
    file: ./secret-jore3importer-importer-db-database
  jore3importer-importer-db-hostname:
    file: ./secret-jore3importer-importer-db-hostname
  jore3importer-importer-db-password:
    file: ./secret-jore3importer-importer-db-password
  jore3importer-importer-db-username:
    file: ./secret-jore3importer-importer-db-username
  jore3importer-jore4-db-database:
    file: ./secret-jore3importer-jore4-db-database
  jore3importer-jore4-db-hostname:
    file: ./secret-jore3importer-jore4-db-hostname
  jore3importer-jore4-db-password:
    file: ./secret-jore3importer-jore4-db-password
  jore3importer-jore4-db-username:
    file: ./secret-jore3importer-jore4-db-username
  jore3importer-source-db-database:
    file: ./secret-jore3importer-source-db-database
  jore3importer-source-db-hostname:
    file: ./secret-jore3importer-source-db-hostname
  jore3importer-source-db-password:
    file: ./secret-jore3importer-source-db-password
  jore3importer-source-db-port:
    file: ./secret-jore3importer-source-db-port
  jore3importer-source-db-username:
    file: ./secret-jore3importer-source-db-username
  mapmatching-db-password:
    file: ./secret-mapmatching-db-password
  mapmatching-db-username:
    file: ./secret-mapmatching-db-username
  mapmatchingdb-postgres-password:
    file: ./secret-mapmatchingdb-postgres-password
  mapmatchingdb-postgres-user:
    file: ./secret-mapmatchingdb-postgres-user
  testdb-db-auth-name:
    file: ./secret-testdb-db-auth-name
  testdb-db-auth-password:
    file: ./secret-testdb-db-auth-password
  testdb-db-auth-username:
    file: ./secret-testdb-db-auth-username
  testdb-db-hasura-name:
    file: ./secret-testdb-db-hasura-name
  testdb-db-hasura-password:
    file: ./secret-testdb-db-hasura-password
  testdb-db-hasura-username:
    file: ./secret-testdb-db-hasura-username
  testdb-db-jore3importer-name:
    file: ./secret-testdb-db-jore3importer-name
  testdb-db-jore3importer-password:
    file: ./secret-testdb-db-jore3importer-password
  testdb-db-jore3importer-username:
    file: ./secret-testdb-db-jore3importer-username
  testdb-db-timetables-name:
    file: ./secret-testdb-db-timetables-name
