{{- range $name, $srvConfig := .Values.e2eServices }}
{{- range $instanceConfig := $srvConfig }}
{{/* generate patched template copies for configured e2e services */}}
{{- $originalConfig := (index $.Values.microServices $name) }}
{{- $patchedConfig := (coll.Merge ((print
`{
  "serviceName": "` $name "-" $instanceConfig.serviceNamePostfix `",
  "localSecrets": ` ((or (index $instanceConfig "localSecrets") (dict)) | toJSON) `,
  "ports": ` ((or (index $instanceConfig "ports") (dict)) | toJSON) `
}`
) | json) $originalConfig ) }}
{{- tmpl.Exec "templates/compose-service.yaml" $patchedConfig }}
{{- end -}}
{{- end -}}
