{{- if (index . "localSecrets") }}
{{- range $secretName, $secretValue := .localSecrets }}
  {{ $.serviceName }}-{{ $secretName }}:
    file: ./secret-{{ $.serviceName }}-{{ $secretName }}
  {{- /* also create the secret files on the fly */}}
  {{- file.Write (print "/tmp/clusters/docker-compose/secret-" $.serviceName "-" $secretName) (print $secretValue "\n")}}
{{- end }}
{{- end -}}
