# This is a generated file, all modifications will be overwritten!

---
version: "3.8"
services:
{{- range $srv := .Values.microServices }}
{{ tmpl.Exec "templates/compose-service.yaml" $srv }}
{{- end }}
{{ tmpl.Exec "templates/compose-e2e-services.yaml" . }}
  jore4-proxy:
    container_name: proxy
    image: nginx:alpine
    restart: "unless-stopped"
    networks:
      - jore4
    ports:
      - "127.0.0.1:3300:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
{{- /* rendering nginx.conf to a file that will be mapped as a volume */}}
{{- file.Write "/tmp/clusters/docker-compose/nginx.conf" (tmpl.Exec "templates/nginx.conf") }}

networks:
  jore4:

secrets:
{{- range $srv := .Values.microServices }}
{{- tmpl.Exec "templates/compose-secrets.yaml" $srv -}}
{{- end }}
{{- tmpl.Exec "templates/compose-e2e-secrets.yaml" . }}
